[pytest]
filterwarnings =
    ignore:.*'crypt'.* is deprecated and slated for removal in Python 3.13:DeprecationWarning
    ignore:.*'audioop'.* is deprecated and slated for removal in Python 3.13:DeprecationWarning
